name: Terraform PR
on:
  pull_request:
    branches:
      - main
    paths:
      - 'infrastructure/'
      - 'kubernetes/'

jobs:
  infrastructure:
    name: Plan Infrastructure
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infrastructure
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_hostname: 'app.terraform.io'
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
          terraform_version: 1.4
          terraform_wrapper: false
      - run: terraform init
      - run: terraform validate
      - run: terraform plan -no-color
  kubernetes:
    name: Plan Kubernetes
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: kubernetes
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_hostname: 'app.terraform.io'
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
          terraform_version: 1.4
          terraform_wrapper: false
      - run: terraform init
      - run: terraform validate
      - run: terraform plan -no-color
